# These are supported funding model platforms

github: skyzyx
patreon: skyzyx
ko_fi: readmeguide
liberapay: readmeguide
custom: ['https://cash.me/$rparman', 'https://www.paypal.me/rparman', 'https://venmo.com/skyzyx']
